name: Build, Release & Upload

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Use a supported version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Create release artifact
        run: |
          mkdir release
          cp build/app/outputs/apk/release/* release/
          cp build/ios/iphoneos/app.ipa release/
          zip -r release.zip release/
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
      - name: Push to Releases
        id: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}. Release URL: https://github.com/${{ github.repository }}/releases/tag/v1.0.${{ github.run_number }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  upload-to-gdrive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: release
      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: release.zip
          name: release.zip
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_KEY }}
          encoded: false
