on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Archive
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Archive release files
        id: archive
        run: |
          mkdir -p $GITHUB_WORKSPACE/build/release
          zip -r $GITHUB_WORKSPACE/build/release/release_archive.zip build/app/outputs/apk/release build/ios/iphoneos/app.ipa
      - name: List files in release directory (for debugging)
        run: ls -la $GITHUB_WORKSPACE/build/release

  upload:
    name: Upload & Notify
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List files in release directory (for debugging)
        run: ls -la $GITHUB_WORKSPACE/build/release
      - name: Upload release to Google Drive
        id: upload_to_gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_KEY }}
          filename: ${{ github.workspace }}/build/release/release_archive.zip
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          name: "release_v1.0.${{ github.run_number }}.zip" # optional string
          overwrite: "true" # optional boolean
      - name: Send release link to Slack
        run: |
          UPLOAD_URL=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GDRIVE_KEY }}" \
            "https://www.googleapis.com/drive/v3/files/${{ steps.upload_to_gdrive.outputs.fileId }}?alt=media" \
            | jq -r '.webViewLink')
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}\nDownload link: '$UPLOAD_URL'"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
