on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Upload build artifacts to Google Drive
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/app/outputs/apk/release/*
            build/ios/iphoneos/app.ipa

  upload:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./build
      - name: Upload to Google Drive
        uses: mkrakowitzer/actions-googledrive@master
        with:
          upload-from: ./build
          upload-to: ${{ secrets.GDRIVE_FOLDER_ID }}
          skicka-tokencache-json: ${{ secrets.GDRIVE_KEY }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      - name: Send notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
