on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-x86_64-release.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Send notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New Flutter release build is available. Version: v1.0.${{ github.run_number }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

  upload-to-drive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload APK to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_KEY }}
          filename: "build/app/outputs/apk/release/app-x86_64-release.apk"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          name: "app-x86_64-release_v1.0.${{ github.run_number }}.apk"
          overwrite: "true"

      - name: Upload IPA to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_KEY }}
          filename: "build/ios/iphoneos/app.ipa"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          name: "app_v1.0.${{ github.run_number }}.ipa"
          overwrite: "true"
